# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerData', '0001_initial'),
        ('AssetData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currOwn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerData.Customer')),
            ],
        ),
    ]
