# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 00:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetData', '0002_currentowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='dateRented',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
