# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetData', '0003_asset_daterented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentowner',
            name='currOwn',
        ),
        migrations.DeleteModel(
            name='currentOwner',
        ),
    ]
